#!/bin/bash
set -euf -o pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";

BEACONROOT_BYTECODE="$(geas "src/beacon_root/main.eas")"
WITHDRAWALS_BYTECODE="$(geas "src/withdrawals/main.eas")"
CONSOLODATIONS_BYTECODE="$(geas "src/consolidations/main.eas")"
FAKE_EXPO_BYTECODE="$(geas "src/common/fake_expo_test.eas")"

sed \
    -e "s/@bytecode@/$BEACONROOT_BYTECODE/" \
    "$SCRIPT_DIR/test/BeaconRoot.t.sol.in" > "$SCRIPT_DIR/test/BeaconRoot.t.sol"

sed \
    -e "s/@bytecode@/$WITHDRAWALS_BYTECODE/" \
    -e "s/@bytecode_expo@/$FAKE_EXPO_BYTECODE/" \
    "$SCRIPT_DIR/test/Withdrawal.t.sol.in" > "$SCRIPT_DIR/test/Withdrawal.t.sol"

sed \
    -e "s/@bytecode@/$WITHDRAWALS_BYTECODE/" \
    "$SCRIPT_DIR/test/halmos/EIP7002.t.sol.in" > "$SCRIPT_DIR/test/halmos/EIP7002.t.sol"

sed \
    -e "s/@bytecode@/$FAKE_EXPO_BYTECODE/" \
    "$SCRIPT_DIR/test/FakeExpo.t.sol.in" > "$SCRIPT_DIR/test/FakeExpo.t.sol"

sed \
    -e "s/@bytecode@/$CONSOLODATIONS_BYTECODE/" \
    -e "s/@bytecode_expo@/$FAKE_EXPO_BYTECODE/" \
    "$SCRIPT_DIR/test/Consolidation.t.sol.in" > "$SCRIPT_DIR/test/Consolidation.t.sol"

forge "$@" --evm-version shanghai
